# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 16
#       uses: actions/setup-java@v2
#       with:
#         java-version: '16'
#         distribution: 'adopt'
#     - name: Build with Maven
#       run: mvn -B package --file pom.xml
      
  test:
    
    runs-on: ubuntu-latest
    env:
      MYSQL_URL: ${{ secrets.MYSQL_URL }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    
#     - name: Cache SonarCloud packages
#       uses: actions/cache@v1
#       with:
#         path: ~/.sonar/cache
#         key: ${{ runner.os }}-sonar
#         restore-keys: ${{ runner.os }}-sonar
        
#     - name: Cache Maven packages
#       uses: actions/cache@v1
#       with:
#         path: ~/.m2
#         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#         restore-keys: ${{ runner.os }}-m2
      
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
      
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: ${{ env.MYSQL_PASSWORD }}
        mysql database: db_test
        
    - name: jacoco-badge-generator
      uses: cicirello/jacoco-badge-generator@v2.3.0
      
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
